# Package Overview
package_name: regression_model

# Data Files
training_data_file: titanic.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (sale price)
target: survived

pipeline_name: regression_model
pipeline_save_file: regression_model_output_v

features:
  - age
  - fare
  - sex
  - cabin
  - embarked
  - title

numerical_vars:
  - age
  - fare

categorical_vars:
  - sex
  - cabin
  - embarked
  - title



cabin_vars:
  - cabin

# set train/test split
test_size: 0.1

# to set the random seed
random_state: 0

C: 0.005

